/* Restaurant entry for DB */
{"restaurant_name": "Caspian", "meal_time": ["breakfast", "lunch", "dinner"], "food_category": ["mediterranean", "american"], "price": "min", "goal_meal": ["egg", "curry", "salad", "quesadilla", "burger", "gyro", "falafel", "burrito"]},
{"restaurant_name": "Rennies_Landing", "meal_time": ["breakfast", "lunch", "dinner"], "food_category": ["pubfood", "american"], "price": "min", "goal_meal": ["egg", "chicken", "gardenburger", "steak", "nacho", "hotwing", "pancake", "salad", "quesadilla", "burger", "gyro", "falafel"]},
{"restaurant_name": "Qdoba", "meal_time": ["breakfast", "lunch", "dinner"], "food_category": ["mexican"], "price": "min", "goal_meal": ["egg", "burrito", "nacho", "gumbo", "taco", "salad", "quesadilla", "chip"]},
{"restaurant_name": "East_Meets_West", "meal_time": ["lunch", "dinner"], "food_category": ["asian"], "price": "min", "goal_meal": ["fried_rice", "soup", "noodle", "chow mein", "shrimp", "pork", "chicken", "beef", "rice"]},
{"restaurant_name": "Glenwood", "meal_time": ["breakfast", "lunch", "dinner"], "food_category": ["american", "asian"], "price": "med", "goal_meal": ["egg", ,"burrito"]},
{"restaurant_name": "Webfoot_Bar_and_Grill", "meal_time": ["breakfast", "lunch", "dinner"], "food_category": ["american", "pubfood"], "price": "med", "goal_meal": ["egg", "sandwich", "nacho", "salad", "burrito"]},
{"restaurant_name": "Alder_Street_Fish_Co", "meal_time": ["lunch", "dinner"], "food_category": ["american"], "price": "med", "goal_meal": ["fish_and_chip", "sandwich", "burger", "soup", "salad", "fish"]},
{"restaurant_name": "Sweet_Basil_Express", "meal_time": ["lunch", "dinner"], "food_category": ["thai"], "price": "min", "goal_meal": ["pad thai", "noodle", "soup", "rice", "fried_rice", "curry"]},
{"restaurant_name": "DairyQueen", "meal_time": ["lunch", "dinner", "dessert"], "food_category": ["american"], "price": "min", "goal_meal": ["burger", "salad", "cake", "chicken", "ice cream"]},
{"restaurant_name": "DoughCo", "meal_time": ["lunch", "dinner"], "food_category": ["italian"], "price": "min", "goal_meal": ["calzone", "chicken"]},
{"restaurant_name": "Pegasus_Pizza", "meal_time": ["lunch", "dinner"], "food_category": ["italian"], "price": "med", "goal_meal": ["pizza", "salad", "calzone", "sandwich"]},
{"restaurant_name": "Porcellino_Bistro", "meal_time": ["lunch", "dinner"], "food_category": ["italian", "american"], "price": "med", "goal_meal": ["pizza", "salad", "sandwich", "panini"]},
{"restaurant_name": "Sy's Pizza", "meal_time": ["lunch", "dinner"], "food_category": ["italian"], "price": "min", "goal_meal": ["pizza"]},
{"restaurant_name": "Taylor's Bar & Grill", "meal_time": ["breakfast", "lunch", "dinner"], "food_category": ["pubfood", "american"], "price": "min", "goal_meal": ["egg", "sandwich", "chicken", "gardenburger", "steak", "nacho", "hotwing", "pancake", "salad", "quesadilla", "burger"]},
{"restaurant_name": "Evergreen_Indian_Restaurant", "meal_time": ["lunch", "dinner"], "food_category": ["asian"], "price": "med", "goal_meal": ["curry", "chicken", "lamb", "masala", "rice", "seafood"]},
{"restaurant_name": "Cafe_Siena", "meal_time": ["breakfast", "lunch"], "food_category": ["american", "mexican"], "price": "min", "goal_meal": ["bagel", "sandwich", "egg", "crepe", "burrito", "rice", "bean", "chicken", "potato"]},
{"restaurant_name": "Wild_Duck_Cafe", "meal_time": ["breakfast", "lunch", "dinner"], "food_category": ["american", "italian"], "price": "med", "goal_meal": ["egg", "waffle", "pancake", "chip", "burger", "chicken", "nacho", "fries", "sandwich", "salmon", "pasta", "soup", "salad", "steak", "macaroni"]},
{"restaurant_name": "Track_Town_Pizza", "meal_time": ["lunch", "dinner"], "food_category": ["italian"], "price": "max", "goal_meal": ["pizza", "salad"]},
{"restaurant_name": "Excelsior_Inn_and_Risorante_Italiano", "meal_time": ["breakfast", "lunch", "dinner"], "food_category": ["italian"], "price": "max", "goal_meal": ["egg", "pasta", "pizza", "salad", "burger", "seafood", "shrimp", "salmon"]},
{"restaurant_name": "Noodle_Head", "meal_time": ["lunch", "dinner"], "food_category": ["asian"], "price": "min", "goal_meal": ["noodle", "pasta", "chicken", "pork", "beef", "pho", "soup"]},
{"restaurant_name": "Cafe_Seoul", "meal_time": ["lunch", "dinner"], "food_category": ["asian"], "price": "min", "goal_meal": ["soup", "rice", "teriyaki", "noodle", "chicken", "beef"]},
{"restaurant_name": "Maple_Garden", "meal_time": ["lunch", "dinner"], "food_category": ["asian"], "price": "min", "goal_meal": ["soup", "fried_rice", "rice", "chicken", "beef", "shrimp", "noodle"]},
{"restaurant_name": "Teriyaki_Boy", "meal_time": ["lunch", "dinner"], "food_category": ["asian"], "price": "min", "goal_meal": ["rice", "chicken", "shrimp", "fried_rice", "tofu", "sushi"]},
{"restaurant_name": "Barry's_Espresso", "meal_time": ["breakfast", "lunch", "dessert"], "food_category": ["american"], "price": "min", "goal_meal": ["bagel", "sandwich", "panini", "hot_dog", "salad", "cookie", "egg", "bacon"]},
{"restaurant_name": "Yogurt_Extreme", "meal_time": ["dessert"], "food_category": ["american"], "price": "min", "goal_meal": ["frozen_yogurt", "chocolate"]},
{"restaurant_name": "Milky_Way", "meal_time": ["breakfast", "lunch"], "food_category": ["american", "asian"], "price": "min", "goal_meal": ["bagel", "sandwich"]},
{"restaurant_name": "Peachwave", "meal_time": ["dessert", "lunch", "dinner"], "food_category": ["american, asian"], "price": "min", "goal_meal": ["frozen_yogurt", "sushi"]}


