/* Database info */

{"restaurant_name": "Caspian", "meal_time": ["breakfast", "lunch", "dinner"], "food_category": ["mediterranean", "american"], "price": "min"},
{"restaurant_name": "Rennies_Landing", "meal_time": ["breakfast", "lunch", "dinner"], "food_category": ["pubfood", "american"], "price": "min"},
{"restaurant_name": "Qdoba", "meal_time": ["breakfast", "lunch", "dinner"], "food_category": ["mexican"], "price": "min"},
{"restaurant_name": "East_Meets_West", "meal_time": ["lunch", "dinner"], "food_category": ["asian"], "price": "min"},
{"restaurant_name": "Glenwood", "meal_time": ["breakfast", "lunch", "dinner"], "food_category": ["american", "asian"], "price": "med"},
{"restaurant_name": "Webfoot_Bar_and_Grill", "meal_time": ["breakfast", "lunch", "dinner"], "food_category": ["american", "pubfood"], "price": "med"},
{"restaurant_name": "Alder_Street_Fish_Co", "meal_time": ["lunch", "dinner"], "food_category": ["american"], "price": "med"},
{"restaurant_name": "Sweet_Basil_Express", "meal_time": ["lunch", "dinner"], "food_category": ["thai"], "price": "min"},
{"restaurant_name": "DairyQueen", "meal_time": ["lunch", "dinner", "dessert"], "food_category": ["american"], "price": "min"},
{"restaurant_name": "DoughCo", "meal_time": ["lunch", "dinner"], "food_category": ["italian"], "price": "min"},
{"restaurant_name": "Pegasus_Pizza", "meal_time": ["lunch", "dinner"], "food_category": ["italian"], "price": "med"},
{"restaurant_name": "Porcellino_Bistro", "meal_time": ["lunch", "dinner"], "food_category": ["italian", "american"], "price": "med"},
{"restaurant_name": "Sy's_Pizza", "meal_time": ["lunch", "dinner"], "food_category": ["italian"], "price": "min"},
{"restaurant_name": "Taylor's_Bar_&_Grill", "meal_time": ["breakfast", "lunch", "dinner"], "food_category": ["pubfood", "american"], "price": "min"},
{"restaurant_name": "Evergreen_Indian_Restaurant", "meal_time": ["lunch", "dinner"], "food_category": ["asian"], "price": "med"},
{"restaurant_name": "Cafe_Siena", "meal_time": ["breakfast", "lunch"], "food_category": ["american", "mexican"], "price": "min"},
{"restaurant_name": "Wild_Duck_Cafe", "meal_time": ["breakfast", "lunch", "dinner"], "food_category": ["american", "italian"], "price": "med"},
{"restaurant_name": "Track_Town_Pizza", "meal_time": ["lunch", "dinner"], "food_category": ["italian"], "price": "max", "goal_meal": ["pizza", "salad"]},
{"restaurant_name": "Excelsior_Inn_and_Risorante_Italiano", "meal_time": ["breakfast", "lunch", "dinner"], "food_category": ["italian"], "price": "max"},
{"restaurant_name": "Noodle_Head", "meal_time": ["lunch", "dinner"], "food_category": ["asian"], "price": "min"},
{"restaurant_name": "Cafe_Seoul", "meal_time": ["lunch", "dinner"], "food_category": ["asian"], "price": "min"},
{"restaurant_name": "Maple_Garden", "meal_time": ["lunch", "dinner"], "food_category": ["asian"], "price": "min"},
{"restaurant_name": "Teriyaki_Boy", "meal_time": ["lunch", "dinner"], "food_category": ["asian"], "price": "min"},
{"restaurant_name": "Barry's_Espresso", "meal_time": ["breakfast", "lunch", "dessert"], "food_category": ["american"], "price": "min"},
{"restaurant_name": "Yogurt_Extreme", "meal_time": ["dessert"], "food_category": ["american"], "price": "min"},
{"restaurant_name": "Milky_Way", "meal_time": ["breakfast", "lunch"], "food_category": ["american", "asian"], "price": "min"},
{"restaurant_name": "Peachwave", "meal_time": ["dessert", "lunch", "dinner"], "food_category": ["american, asian"], "price": "min"}
