
/* Database info */

{"restaurant_name": "Caspian", "meal_time": ["breakfast", "lunch", "dinner"], "food_category": ["mediterranean", "american"], "price": "min"},
{"restaurant_name": "RenniesLanding", "meal_time": ["breakfast", "lunch", "dinner"], "food_category": ["pubfood", "american"], "price": "min"},
{"restaurant_name": "Qdoba", "meal_time": ["breakfast", "lunch", "dinner"], "food_category": ["mexican"], "price": "min"},
{"restaurant_name": "East Meets West", "meal_time": ["lunch", "dinner"], "food_category": ["asian"], "price": "min"},
{"restaurant_name": "Glenwood", "meal_time": ["breakfast", "lunch", "dinner"], "food_category": ["american", "asian"], "price": "med"},
{"restaurant_name": "Webfoot Bar and Grill", "meal_time": ["breakfast", "lunch", "dinner"], "food_category": ["american", "pubfood"], "price": "med"},
{"restaurant_name": "Alder Street Fish Co", "meal_time": ["lunch", "dinner"], "food_category": ["american"], "price": "med"},
{"restaurant_name": "Sweet Basil Express", "meal_time": ["lunch", "dinner"], "food_category": ["thai"], "price": "min"},
{"restaurant_name": "DairyQueen", "meal_time": ["lunch", "dinner", "dessert"], "food_category": ["american"], "price": "min"},
{"restaurant_name": "DoughCo", "meal_time": ["lunch", "dinner"], "food_category": ["italian"], "price": "min"},
{"restaurant_name": "Pegasus Pizza", "meal_time": ["lunch", "dinner"], "food_category": ["italian"], "price": "med"},
{"restaurant_name": "Porcellino Bistro", "meal_time": ["lunch", "dinner"], "food_category": ["italian", "american"], "price": "med"},
{"restaurant_name": "Sys Pizza", "meal_time": ["lunch", "dinner"], "food_category": ["italian"], "price": "min"},
{"restaurant_name": "Taylors Bar and Grill", "meal_time": ["breakfast", "lunch", "dinner"], "food_category": ["pubfood", "american"], "price": "min"},
{"restaurant_name": "Evergreen Indian Restaurant", "meal_time": ["lunch", "dinner"], "food_category": ["asian"], "price": "med"},
{"restaurant_name": "Cafe Siena", "meal_time": ["breakfast", "lunch"], "food_category": ["american", "mexican"], "price": "min"},
{"restaurant_name": "Wild Duck Cafe", "meal_time": ["breakfast", "lunch", "dinner"], "food_category": ["american", "italian"], "price": "med"},
{"restaurant_name": "Track Town Pizza", "meal_time": ["lunch", "dinner"], "food_category": ["italian"], "price": "max", "goal_meal": ["pizza", "salad"]},
{"restaurant_name": "Excelsior Inn and Risorante Italiano", "meal_time": ["breakfast", "lunch", "dinner"], "food_category": ["italian"], "price": "max"},
{"restaurant_name": "Noodle Head", "meal_time": ["lunch", "dinner"], "food_category": ["asian"], "price": "min"},
{"restaurant_name": "Cafe Seoul", "meal_time": ["lunch", "dinner"], "food_category": ["asian"], "price": "min"},
{"restaurant_name": "Maple Garden", "meal_time": ["lunch", "dinner"], "food_category": ["asian"], "price": "min"},
{"restaurant_name": "Teriyaki Boy", "meal_time": ["lunch", "dinner"], "food_category": ["asian"], "price": "min"},
{"restaurant_name": "Barrys Espresso", "meal_time": ["breakfast", "lunch", "dessert"], "food_category": ["american"], "price": "min"},
{"restaurant_name": "Yogurt Extreme", "meal_time": ["dessert"], "food_category": ["american"], "price": "min"},
{"restaurant_name": "Milky Way", "meal_time": ["breakfast", "lunch"], "food_category": ["american", "asian"], "price": "min"},
{"restaurant_name": "Peachwave", "meal_time": ["dessert", "lunch", "dinner"], "food_category": ["american, asian"], "price": "min"}
